namespace GTA.UI
{
    using System;

    public enum HudComponent
    {
        WantedStars = 1,
        WeaponIcon = 2,
        Cash = 3,
        MpCash = 4,
        MpMessage = 5,
        VehicleName = 6,
        AreaName = 7,
        Unused = 8,
        StreetName = 9,
        HelpText = 10,
        FloatingHelpText1 = 11,
        FloatingHelpText2 = 12,
        CashChange = 13,
        Reticle = 14,
        SubtitleText = 15,
        RadioStationsWheel = 0x10,
        Saving = 0x11,
        GamingStreamUnusde = 0x12,
        WeaponWheel = 0x13,
        WeaponWheelStats = 20,
        DrugsPurse01 = 0x15,
        DrugsPurse02 = 0x16,
        DrugsPurse03 = 0x17,
        DrugsPurse04 = 0x18,
        MpTagCashFromBank = 0x19,
        MpTagPackages = 0x1a,
        MpTagCuffKeys = 0x1b,
        MpTagDownloadData = 0x1c,
        MpTagIfPedFollowing = 0x1d,
        MpTagKeyCard = 30,
        MpTagRandomObject = 0x1f,
        MpTagRemoteControl = 0x20,
        MpTagCashFromSafe = 0x21,
        MpTagWeaponsPackage = 0x22,
        MpTagKeys = 0x23,
        MpVehicle = 0x24,
        MpVehicleHeli = 0x25,
        MpVehiclePlane = 0x26,
        PlayerSwitchAlert = 0x27,
        MpRankBar = 40,
        DirectorMode = 0x29,
        ReplayController = 0x2a,
        ReplayMouse = 0x2b,
        ReplayHeader = 0x2c,
        ReplayOptions = 0x2d,
        ReplayHelpText = 0x2e,
        ReplayMiscText = 0x2f,
        ReplayTopLine = 0x30,
        ReplayBottomLine = 0x31,
        ReplayLeftBar = 50,
        ReplayTimer = 0x33
    }
}

